const priceDishes = [
  {
    image: 'https://i.ibb.co/39wFD6fr/20230721142523-fpdl-1-1.png',
    span: 'Indian Dessert',
    name: 'Angoori Rasmalai',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    commentSpan: '(100)',
    price: '₹250',
    button: 'Buy Now',
  },
  {
    image: 'https://i.ibb.co/RGtCsTJ2/20230720134636-fpdl.png',
    span: 'Indian',
    name: 'Tea Time Snacks',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    commentSpan: '(80)',
    price: '₹250',
    button: 'Buy Now',
  },
  {
    image: 'https://i.ibb.co/W4Bjwhwx/20230720134751-fpdl.png',
    span: 'Indian',
    name: 'Tea Time Snacks',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    commentSpan: '(50)',
    price: '₹200',
    button: 'Buy Now',
  },
  {
    image: 'https://i.ibb.co/S49xywCy/20230720135940-fpdl.png',
    span: 'South Indian',
    name: 'Masala Dosa',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    commentSpan: '(120)',
    price: '₹150',
    button: 'Buy Now',
  },
  {
    image: 'https://i.ibb.co/VcYL34JJ/20230720140127-fpdl.png',
    span: 'Gujarati',
    name: 'Pav Bhaji',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    commentSpan: '(50)',
    price: '₹250',
    button: 'Buy Now',
  },
  {
    image: 'https://i.ibb.co/60GvWXWn/DAL-BAATI-CHURMA.png',
    span: 'Rajasthan',
    name: 'Dal Bati Churma',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    imageStar: 'https://i.ibb.co/8g4Ctdwk/Star-1.png',
    commentSpan: '(500)',
    price: '₹450',
    button: 'Buy Now',
  },
];
