const bestSnacks = [
  {
    image: 'https://i.ibb.co/PsWWdh9V/20230720134751-fpdl.jpg',
    name: 'Indian Vegetable Pulao',
    rating: 4,
    span: '(50)',
    price: '₹200',
    buttonImageMinus: 'https://i.ibb.co/Y43GDLzf/Outline.png',
    count: '00',
    buttonImagePlus: 'https://i.ibb.co/jvQnf4Dm/plus.png',
    button: 'ADD TO CART',
  },
  {
    image: 'https://i.ibb.co/CKD7DL7d/image-9.png',
    name: 'Paneer Bhuna Masala',
    rating: 5,
    span: '(75)',
    price: '₹250',
    buttonImageMinus: 'https://i.ibb.co/Y43GDLzf/Outline.png',
    count: '00',
    buttonImagePlus: 'https://i.ibb.co/jvQnf4Dm/plus.png',
    button: 'ADD TO CART',
  },
  {
    image: 'https://i.ibb.co/KcdW03fx/image-10.png',
    name: 'Vermicelli italiano Upma',
    rating: 3,
    span: '(30)',
    price: '₹180',
    buttonImageMinus: 'https://i.ibb.co/Y43GDLzf/Outline.png',
    count: '00',
    buttonImagePlus: 'https://i.ibb.co/jvQnf4Dm/plus.png',
    button: 'ADD TO CART',
  },
];
