// const bestDishes = [
//   {
//     image: 'https://i.ibb.co/TqHzyV3y/20230716194412-fpdl-1-1.png',
//     name: 'Indian Vegetable Pulao',
//     imageStar: 'https://i.ibb.co/GQ31hr09/Star-1.png',
//     span: '(50)',
//     price: '₹200',
//     buttonImageMinus: 'https://i.ibb.co/Y43GDLzf/Outline.png',
//     count: '00',
//     buttonImagePlus: 'https://i.ibb.co/jvQnf4Dm/plus.png',
//     button: 'ADD TO CART',
//   },
//   {
//     image:
//       'https://i.ibb.co/k2VbyKNY/vertical-shot-traditional-indian-paneer-butter-masala-cheese-cottage-curry-black-surface-1.png',
//     name: 'Paneer Bhuna Masala',
//     imageStar: 'https://i.ibb.co/GQ31hr09/Star-1.png',
//     span: '(50)',
//     price: '₹200',
//     buttonImageMinus: 'https://i.ibb.co/Y43GDLzf/Outline.png',
//     count: '00',
//     buttonImagePlus: 'https://i.ibb.co/jvQnf4Dm/plus.png',
//     button: 'ADD TO CART',
//   },
//   {
//     image: 'https://i.ibb.co/TqHzyV3y/20230716194412-fpdl-1-1.png',
//     name: 'Vermicelli Upma',
//     imageStar: 'https://i.ibb.co/GQ31hr09/Star-1.png',
//     span: '(50)',
//     price: '₹200',
//     buttonImageMinus: 'https://i.ibb.co/Y43GDLzf/Outline.png',
//     count: '00',
//     buttonImagePlus: 'https://i.ibb.co/jvQnf4Dm/plus.png',
//     button: 'ADD TO CART',
//   },
// ];

const bestDishes = [
  {
    image: 'https://i.ibb.co/TqHzyV3y/20230716194412-fpdl-1-1.png',
    name: 'Indian Vegetable Pulao',
    rating: 4,
    span: '(50)',
    price: '₹200',
    buttonImageMinus: 'https://i.ibb.co/Y43GDLzf/Outline.png',
    count: '00',
    buttonImagePlus: 'https://i.ibb.co/jvQnf4Dm/plus.png',
    button: 'ADD TO CART',
  },
  {
    image:
      'https://i.ibb.co/k2VbyKNY/vertical-shot-traditional-indian-paneer-butter-masala-cheese-cottage-curry-black-surface-1.png',
    name: 'Paneer Bhuna Masala',
    rating: 5,
    span: '(75)',
    price: '₹250',
    buttonImageMinus: 'https://i.ibb.co/Y43GDLzf/Outline.png',
    count: '00',
    buttonImagePlus: 'https://i.ibb.co/jvQnf4Dm/plus.png',
    button: 'ADD TO CART',
  },
  {
    image: 'https://i.ibb.co/TqHzyV3y/20230716194412-fpdl-1-1.png',
    name: 'Vermicelli italiano Upma',
    rating: 3,
    span: '(30)',
    price: '₹180',
    buttonImageMinus: 'https://i.ibb.co/Y43GDLzf/Outline.png',
    count: '00',
    buttonImagePlus: 'https://i.ibb.co/jvQnf4Dm/plus.png',
    button: 'ADD TO CART',
  },
  //   {
  //     image: 'http://googleusercontent.com/file_content/0',
  //     name: 'Angoori Rasmalai',
  //     rating: 4,
  //     span: '(100)',
  //     price: '₹250',
  //     buttonImageMinus: 'https://i.ibb.co/Y43GDLzf/Outline.png',
  //     count: '00',
  //     buttonImagePlus: 'https://i.ibb.co/jvQnf4Dm/plus.png',
  //     button: 'BUY NOW',
  //   },
];
