const bestRegularData = [
  {
    image: 'https://i.ibb.co/tw7z93Ld/20230720135940-fpdl.png',
    name: 'Masala Dosa',
    rating: 4,
    span: '(50)',
    price: '₹200',
    buttonImageMinus: 'https://i.ibb.co/Y43GDLzf/Outline.png',
    count: '00',
    buttonImagePlus: 'https://i.ibb.co/jvQnf4Dm/plus.png',
    button: 'ADD TO CART',
  },
  {
    image: 'https://i.ibb.co/PZcry1jj/20230720134636-fpdl.png',
    name: 'Pav Bhaji',
    rating: 4,
    span: '(50)',
    price: '₹200',
    buttonImageMinus: 'https://i.ibb.co/Y43GDLzf/Outline.png',
    count: '00',
    buttonImagePlus: 'https://i.ibb.co/jvQnf4Dm/plus.png',
    button: 'ADD TO CART',
  },
  {
    image: 'https://i.ibb.co/677p8Xc6/DAL-BAATI-CHURMA.png',
    name: 'Dal Bati Churma',
    rating: 4,
    span: '(50)',
    price: '₹200',
    buttonImageMinus: 'https://i.ibb.co/Y43GDLzf/Outline.png',
    count: '00',
    buttonImagePlus: 'https://i.ibb.co/jvQnf4Dm/plus.png',
    button: 'ADD TO CART',
  },
  {
    image: 'https://i.ibb.co/NgnK7n7x/image-5.png',
    name: 'Puri Sabji',
    rating: 4,
    span: '(50)',
    price: '₹200',
    buttonImageMinus: 'https://i.ibb.co/Y43GDLzf/Outline.png',
    count: '00',
    buttonImagePlus: 'https://i.ibb.co/jvQnf4Dm/plus.png',
    button: 'ADD TO CART',
  },
  {
    image: 'https://i.ibb.co/qFWHDKGj/image-8.png',
    name: 'Naan Bread',
    rating: 4,
    span: '(50)',
    price: '₹200',
    buttonImageMinus: 'https://i.ibb.co/Y43GDLzf/Outline.png',
    count: '00',
    buttonImagePlus: 'https://i.ibb.co/jvQnf4Dm/plus.png',
    button: 'ADD TO CART',
  },
  {
    image: 'https://i.ibb.co/1JzkXD27/image-6.png',
    name: 'Aloo Mutter',
    rating: 4,
    span: '(50)',
    price: '₹200',
    buttonImageMinus: 'https://i.ibb.co/Y43GDLzf/Outline.png',
    count: '00',
    buttonImagePlus: 'https://i.ibb.co/jvQnf4Dm/plus.png',
    button: 'ADD TO CART',
  },
];
